site_name: IT-手册
site_description: "IT 手册整理"
site_author: hlh

theme:
  name: material
  language: zh
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest
    - header.autohide
    - footer.copyright
    - footer.text
    - code.annotate
    - content.code
    - material.nav
    - material.switch
    - content.code.copy  # 启用代码块复制功能
  palette:
    - scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate  # 暗模式
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search
  - awesome-pages

markdown_extensions:
  - admonition
  - codehilite
  - footnotes

extra_css:
  - css/extra.css
